[package]
name = "minivm"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.4"
error-chain = "0.10"
llvm-sys = "39"

minivm-syntax = { path = "./syntax" }

[profile.release]
debug = true
